// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vlagent/targetsstatus/index.qtpl:1
package targetsstatus

//line app/vlagent/targetsstatus/index.qtpl:1
import "github.com/VictoriaMetrics/VictoriaMetrics/lib/htmlcomponents"

//line app/vlagent/targetsstatus/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vlagent/targetsstatus/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vlagent/targetsstatus/index.qtpl:3
func StreamTargetsPage(qw422016 *qt422016.Writer, data []targetsData) {
//line app/vlagent/targetsstatus/index.qtpl:3
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head>
    `)
//line app/vlagent/targetsstatus/index.qtpl:7
	htmlcomponents.StreamCommonHeader(qw422016)
//line app/vlagent/targetsstatus/index.qtpl:7
	qw422016.N().S(`
    <title>vlagent / targets</title>
</head>
<body>
    `)
//line app/vlagent/targetsstatus/index.qtpl:11
	htmlcomponents.StreamNavbar(qw422016)
//line app/vlagent/targetsstatus/index.qtpl:11
	qw422016.N().S(`
    <div class="container-fluid py-3">
        <h4 class="mb-3">Targets</h4>
        `)
//line app/vlagent/targetsstatus/index.qtpl:14
	for _, section := range data {
//line app/vlagent/targetsstatus/index.qtpl:14
		qw422016.N().S(`
            <h5 class="mt-4 mb-2 pb-1 border-bottom">`)
//line app/vlagent/targetsstatus/index.qtpl:15
		qw422016.E().S(section.Category)
//line app/vlagent/targetsstatus/index.qtpl:15
		qw422016.N().S(`</h5>
            `)
//line app/vlagent/targetsstatus/index.qtpl:16
		for _, group := range section.Groups {
//line app/vlagent/targetsstatus/index.qtpl:16
			qw422016.N().S(`
                <details class="mb-2" open>
                    <summary class="p-2 bg-light border rounded" id="`)
//line app/vlagent/targetsstatus/index.qtpl:18
			qw422016.E().S(group.Group)
//line app/vlagent/targetsstatus/index.qtpl:18
			qw422016.N().S(`">
                        <a href="#`)
//line app/vlagent/targetsstatus/index.qtpl:19
			qw422016.E().S(group.Group)
//line app/vlagent/targetsstatus/index.qtpl:19
			qw422016.N().S(`" class="text-decoration-none text-dark font-monospace">`)
//line app/vlagent/targetsstatus/index.qtpl:19
			qw422016.E().S(group.Group)
//line app/vlagent/targetsstatus/index.qtpl:19
			qw422016.N().S(`</a>
                        <span class="text-secondary fw-normal ms-2">(`)
//line app/vlagent/targetsstatus/index.qtpl:20
			qw422016.N().D(len(group.Targets))
//line app/vlagent/targetsstatus/index.qtpl:20
			qw422016.N().S(`)</span>
                    </summary>
                    <div class="ms-3 mt-2">
                        `)
//line app/vlagent/targetsstatus/index.qtpl:23
			for _, t := range group.Targets {
//line app/vlagent/targetsstatus/index.qtpl:23
				qw422016.N().S(`
                            <details class="mb-1">
                                <summary class="font-monospace p-1 border-bottom">`)
//line app/vlagent/targetsstatus/index.qtpl:25
				qw422016.E().S(t.Preview)
//line app/vlagent/targetsstatus/index.qtpl:25
				qw422016.N().S(`</summary>
                                <table class="table table-sm table-bordered mt-2">
                                    <thead class="table-light">
                                        <tr>
                                            <th>Field</th>
                                            <th>Value</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        `)
//line app/vlagent/targetsstatus/index.qtpl:34
				for _, field := range t.DebugInfo {
//line app/vlagent/targetsstatus/index.qtpl:34
					qw422016.N().S(`
                                            <tr>
                                                <td>`)
//line app/vlagent/targetsstatus/index.qtpl:36
					qw422016.E().S(field.Name)
//line app/vlagent/targetsstatus/index.qtpl:36
					qw422016.N().S(`</td>
                                                <td class="font-monospace">`)
//line app/vlagent/targetsstatus/index.qtpl:37
					qw422016.E().S(field.Value)
//line app/vlagent/targetsstatus/index.qtpl:37
					qw422016.N().S(`</td>
                                            </tr>
                                        `)
//line app/vlagent/targetsstatus/index.qtpl:39
				}
//line app/vlagent/targetsstatus/index.qtpl:39
				qw422016.N().S(`
                                    </tbody>
                                </table>
                            </details>
                        `)
//line app/vlagent/targetsstatus/index.qtpl:43
			}
//line app/vlagent/targetsstatus/index.qtpl:43
			qw422016.N().S(`
                    </div>
                </details>
            `)
//line app/vlagent/targetsstatus/index.qtpl:46
		}
//line app/vlagent/targetsstatus/index.qtpl:46
		qw422016.N().S(`
        `)
//line app/vlagent/targetsstatus/index.qtpl:47
	}
//line app/vlagent/targetsstatus/index.qtpl:47
	qw422016.N().S(`
    </div>
</body>
</html>
`)
//line app/vlagent/targetsstatus/index.qtpl:51
}

//line app/vlagent/targetsstatus/index.qtpl:51
func WriteTargetsPage(qq422016 qtio422016.Writer, data []targetsData) {
//line app/vlagent/targetsstatus/index.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlagent/targetsstatus/index.qtpl:51
	StreamTargetsPage(qw422016, data)
//line app/vlagent/targetsstatus/index.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line app/vlagent/targetsstatus/index.qtpl:51
}

//line app/vlagent/targetsstatus/index.qtpl:51
func TargetsPage(data []targetsData) string {
//line app/vlagent/targetsstatus/index.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlagent/targetsstatus/index.qtpl:51
	WriteTargetsPage(qb422016, data)
//line app/vlagent/targetsstatus/index.qtpl:51
	qs422016 := string(qb422016.B)
//line app/vlagent/targetsstatus/index.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlagent/targetsstatus/index.qtpl:51
	return qs422016
//line app/vlagent/targetsstatus/index.qtpl:51
}
