{
 "title": "VictoriaLogs - Explorer for Kubernetes logs",
 "tags": [
  "kubernetes",
  "demo",
  "victorialogs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "DS",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "{}" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "{kubernetes.pod_namespace in($namespace)}"
    }
   },
   {
    "name": "level",
    "label": "Level",
    "query": {
     "query": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)} | format if (log.level:\"\") \"unknown\" as log.level "
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "limit", "label": "Limit", "query": "500,1000,2500,5000" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "- The dashboard filters data by `container name`. The data may not be displayed correctly if several containers have the same name\r\n- The description explicitly specifies a `limit for variables`. It is possible that there are more applications in your cluster and they may not be displayed"
     }
    }
   ]
  },
  { "title": "Overview ($namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| stats by (kubernetes.pod_namespace) count()\r\n| count()"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| stats by (kubernetes.container_name) count()\r\n| count()"
    }
   ]
  },
  {
   "title": "Logs volume (per $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| stats by (log.level) count()",
     "legendFormat": "{{ log.level }}"
    }
   ]
  },
  {
   "title": "Top 10 logs by namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| top 10 (kubernetes.pod_namespace)"
    }
   ]
  },
  {
   "title": "Logs by namespace (per $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (kubernetes.pod_namespace) count() logs_count\r\n| filter logs_count: > 0",
     "legendFormat": "{{kubernetes.pod_namespace}}"
    }
   ]
  },
  {
   "title": "Top 50 logs by containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| top 50 (kubernetes.container_name)"
    }
   ]
  },
  {
   "title": "Logs by container (per $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| stats by (kubernetes.container_name) count() logs_count\r\n| filter logs_count: > 0",
     "legendFormat": "{{kubernetes.container_name}}"
    }
   ]
  },
  {
   "title": "Raw logs ($container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top field-value pairs (facets)",
     "type": "table",
     "description": "Shows the most common field-value pairs \n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#facets-pipe",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| facets 5\r\n| sort by(hits) desc"
      }
     ]
    },
    {
     "title": "Top 10 log patterns (collapse_nums)",
     "type": "table",
     "description": "Shows most common log patterns on the time range\n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| collapse_nums prettify\r\n| top 10 by(_msg)"
      }
     ]
    },
    {
     "title": "Logs raw",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "direction": "desc",
       "expr": "{kubernetes.pod_namespace in($namespace), kubernetes.container_name in($container)}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| log.level:in($level)\r\n| sort by (_time) desc\r\n| limit $limit",
       "maxLines": 5000
      }
     ]
    }
   ]
  }
 ]
}