{
 "title": "VictoriaLogs Explorer - Kubernetes",
 "tags": [
  "kubernetes",
  "victorialogs"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_VICTORIALOGS",
    "label": "DS",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "NS", "query": { "query": "_stream:{}" } },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "_stream:{kubernetes.pod_namespace=$namespace} | format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name"
    }
   },
   {
    "name": "container",
    "label": "Сontainer",
    "query": {
     "query": "_stream:{kubernetes.pod_namespace=$namespace} | format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name | kubernetes.pod_labels.app.kubernetes.io/name:in($app)"
    }
   },
   { "name": "limit", "label": "Limit", "query": "500,1000,2500,5000" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Stats by Namespace ($namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| stats by (kubernetes.pod_namespace) count()\r\n| stats count()",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "App",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"} kubernetes.pod_labels.app.kubernetes.io/name:=\"$app\"\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| stats by (kubernetes.pod_labels.app.kubernetes.io/name) count()\r\n| count()",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| stats by (kubernetes.pod_name) count()\r\n| count()",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Container",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=$namespace}\r\n| stats by (kubernetes.container_name) count()\r\n| stats count()",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| stats count()",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Pods - Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| stats by (log.level) count() total\r\n| sort by(total) desc",
       "legendFormat": "{{ log.level }}"
      }
     ]
    },
    {
     "title": "Top 5 logs by namespace",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| stats by (kubernetes.pod_namespace) count() total\r\n| sort by(total) desc \r\n| limit 5",
       "legendFormat": "{{ kubernetes.pod_namespace }}"
      }
     ]
    },
    {
     "title": "Logs total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| stats by (kubernetes.pod_namespace,kubernetes.pod_labels.app.kubernetes.io/name,kubernetes.container_name) count() logs_total",
       "legendFormat": "{{ kubernetes.pod_namespace }}/{{ kubernetes.pod_labels.app.kubernetes.io/name }}/{{ kubernetes.container_name }}"
      }
     ]
    },
    {
     "title": "Logs rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| stats by (kubernetes.pod_namespace,kubernetes.pod_labels.app.kubernetes.io/name,kubernetes.container_name) rate() log_rate\r\n| filter log_rate: > 0",
       "legendFormat": "{{ kubernetes.pod_namespace }}/{{ kubernetes.pod_labels.app.kubernetes.io/name }}/{{ kubernetes.container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats by App ($app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 logs by app",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 277 },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| stats by (kubernetes.pod_labels.app.kubernetes.io/name) count() hits\r\n| sort by (hits) desc\r\n| limit 10"
      }
     ]
    },
    {
     "title": "Logs by level",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 277 },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| stats by (log.level) count() hits\r\n| sort by (hits) desc"
      }
     ]
    },
    {
     "title": "Top field-value pairs (facets)",
     "type": "table",
     "description": "Shows the most common field-value pairs \n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#facets-pipe",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 285 },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| facets 3\r\n| sort by(hits) desc"
      }
     ]
    },
    {
     "title": "Top 10 log patterns (collapse_nums)",
     "type": "table",
     "description": "Shows most common log patterns on the time range\n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 285 },
     "targets": [
      {
       "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| collapse_nums prettify\r\n| top 10 by(_msg)"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats by Container ($container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Logs by container",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=\"$container\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| stats by (kubernetes.container_name) count() hits\r\n| sort by (hits) desc"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=\"$container\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| stats by (log.level) count() \r\n| sort desc",
     "legendFormat": "{{ log.level }}"
    }
   ]
  },
  {
   "title": "Logs raw",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "_stream:{kubernetes.pod_namespace=\"$namespace\", kubernetes.container_name=\"$container\"}\r\n| format if (kubernetes.pod_labels.app.kubernetes.io/name:\"\") \"unknown\" as kubernetes.pod_labels.app.kubernetes.io/name\r\n| kubernetes.pod_labels.app.kubernetes.io/name:in($app)\r\n| format if (log.level:\"\") \"unknown\" as log.level\r\n| limit $limit"
    }
   ]
  }
 ]
}